# 1.

In [16]:
import array as arr

ar1 = arr.array('i',[0,0,0,0,0,0,0,0,0,0])
print(ar1)

ar2 = [[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]
print(ar2)

array('i', [0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


# 2.

In [17]:
import array as arr

ar1 = arr.array('i',[1,1,1,1,1])
print(ar1)

ar2 = [[1,1,1],[1,1,1],[1,1,1]]
print(ar2)

array('i', [1, 1, 1, 1, 1])
[[1, 1, 1], [1, 1, 1], [1, 1, 1]]


# 3.

In [24]:
import array as arr
import random

randomlist = []
for i in range(20):
    n = random.uniform(10,99)
    randomlist.append(n)
print(randomlist)

temp = []
for x in randomlist:
    temp.append(x**2)

ar = arr.array('d',temp)
print(ar)

[85.96184392984512, 43.45757563259413, 27.70517944592055, 98.99265420845101, 95.94693751920232, 53.473565147989255, 95.61972056060934, 15.746415547381446, 75.65757932679381, 37.05834633481245, 55.27057410157099, 61.03508532651724, 77.05143728776922, 79.77711190699618, 92.9884494877077, 79.20948993513329, 76.21820439448601, 36.103963951712856, 25.418714416240487, 18.36766223016373]
array('d', [7389.43861181905, 1888.560879862639, 767.5769681306585, 9799.545587233953, 9205.814819313715, 2859.422169636251, 9143.130960089016, 247.9496025908161, 5724.069309590098, 1373.321033070907, 3054.83636151725, 3725.2816408152403, 5936.9239881110325, 6364.387584221392, 8646.851738127965, 6274.1432957839825, 5809.214681119646, 1303.4962130265815, 646.111042574392, 337.3710158013833])


# 4.

In [21]:
import array as arr
import random

randomlist = []
for i in range(20):
    n = random.uniform(10,99)
    randomlist.append(n)
    
newlist = [x**2 for x in randomlist]
ar = arr.array('d',newlist)
print(ar)

array('d', [620.4245696636425, 9118.429904355475, 8675.892783321537, 7030.595125038797, 1678.685682306855, 4438.878507500209, 8204.83624360027, 4700.96202013862, 8058.058210878213, 3703.223700163033, 5546.984322162337, 7126.221129591078, 7490.189681731858, 6971.600748556097, 1456.9733700811933, 2234.3041075740607, 610.1977628675893, 3894.833204297023, 713.1386038567633, 363.12963409039463])


# 5.

In [27]:
import time
import array as arr
import random


randomlist = []
for i in range(20):
    n = random.uniform(10,99)
    randomlist.append(n)
    
print('วิธี 1')
temp = []
time1 = time.time()
for x in randomlist:
    temp.append(x**2)

ar = arr.array('d',temp)
time2 = time.time()
print('{} มิลลิวินาที'.format((time2-time1)*1000))

print('วิธี 2')
time3 = time.time()
newlist = [x**2 for x in randomlist]
ar = arr.array('d',newlist)
time4 = time.time()
print('{} มิลลิวินาที'.format((time4-time3)*1000))

วิธี 1
0.10991096496582031 มิลลิวินาที
วิธี 2
0.10395050048828125 มิลลิวินาที


# 6.

In [30]:
import numpy as np

list1 = range(10,1000)
x = np.array(list1)
x

array([ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,
        23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,
        36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,
        49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,
        62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,
        75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,
        88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100,
       101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 19

# 7.

In [32]:
import numpy as np

my_list = range(10,2000)
arr1 = np.array(my_list)
arr1[arr1%2==0]

array([  10,   12,   14,   16,   18,   20,   22,   24,   26,   28,   30,
         32,   34,   36,   38,   40,   42,   44,   46,   48,   50,   52,
         54,   56,   58,   60,   62,   64,   66,   68,   70,   72,   74,
         76,   78,   80,   82,   84,   86,   88,   90,   92,   94,   96,
         98,  100,  102,  104,  106,  108,  110,  112,  114,  116,  118,
        120,  122,  124,  126,  128,  130,  132,  134,  136,  138,  140,
        142,  144,  146,  148,  150,  152,  154,  156,  158,  160,  162,
        164,  166,  168,  170,  172,  174,  176,  178,  180,  182,  184,
        186,  188,  190,  192,  194,  196,  198,  200,  202,  204,  206,
        208,  210,  212,  214,  216,  218,  220,  222,  224,  226,  228,
        230,  232,  234,  236,  238,  240,  242,  244,  246,  248,  250,
        252,  254,  256,  258,  260,  262,  264,  266,  268,  270,  272,
        274,  276,  278,  280,  282,  284,  286,  288,  290,  292,  294,
        296,  298,  300,  302,  304,  306,  308,  3

# 8.

In [33]:
import numpy as np

my_list = range(12,900)
arr1 = np.array(my_list)
arr1[arr1%2!=0]

array([ 13,  15,  17,  19,  21,  23,  25,  27,  29,  31,  33,  35,  37,
        39,  41,  43,  45,  47,  49,  51,  53,  55,  57,  59,  61,  63,
        65,  67,  69,  71,  73,  75,  77,  79,  81,  83,  85,  87,  89,
        91,  93,  95,  97,  99, 101, 103, 105, 107, 109, 111, 113, 115,
       117, 119, 121, 123, 125, 127, 129, 131, 133, 135, 137, 139, 141,
       143, 145, 147, 149, 151, 153, 155, 157, 159, 161, 163, 165, 167,
       169, 171, 173, 175, 177, 179, 181, 183, 185, 187, 189, 191, 193,
       195, 197, 199, 201, 203, 205, 207, 209, 211, 213, 215, 217, 219,
       221, 223, 225, 227, 229, 231, 233, 235, 237, 239, 241, 243, 245,
       247, 249, 251, 253, 255, 257, 259, 261, 263, 265, 267, 269, 271,
       273, 275, 277, 279, 281, 283, 285, 287, 289, 291, 293, 295, 297,
       299, 301, 303, 305, 307, 309, 311, 313, 315, 317, 319, 321, 323,
       325, 327, 329, 331, 333, 335, 337, 339, 341, 343, 345, 347, 349,
       351, 353, 355, 357, 359, 361, 363, 365, 367, 369, 371, 37

# 9.

In [35]:
import numpy as np

my_array = np.eye(4,4)
my_array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 10.

In [36]:
import numpy as np

my_array = np.linspace(5,25,100)
my_array

array([ 5.        ,  5.2020202 ,  5.4040404 ,  5.60606061,  5.80808081,
        6.01010101,  6.21212121,  6.41414141,  6.61616162,  6.81818182,
        7.02020202,  7.22222222,  7.42424242,  7.62626263,  7.82828283,
        8.03030303,  8.23232323,  8.43434343,  8.63636364,  8.83838384,
        9.04040404,  9.24242424,  9.44444444,  9.64646465,  9.84848485,
       10.05050505, 10.25252525, 10.45454545, 10.65656566, 10.85858586,
       11.06060606, 11.26262626, 11.46464646, 11.66666667, 11.86868687,
       12.07070707, 12.27272727, 12.47474747, 12.67676768, 12.87878788,
       13.08080808, 13.28282828, 13.48484848, 13.68686869, 13.88888889,
       14.09090909, 14.29292929, 14.49494949, 14.6969697 , 14.8989899 ,
       15.1010101 , 15.3030303 , 15.50505051, 15.70707071, 15.90909091,
       16.11111111, 16.31313131, 16.51515152, 16.71717172, 16.91919192,
       17.12121212, 17.32323232, 17.52525253, 17.72727273, 17.92929293,
       18.13131313, 18.33333333, 18.53535354, 18.73737374, 18.93

# 11.

In [38]:
import numpy as np

x = np.random.rand(1)
x

array([0.27673523])

# 12.

In [42]:
import numpy as np

x = np.random.randint(50,100,(4,4))
print('Matrix \n',x)
t = x.T
print('Transpose \n',t)

Matrix 
 [[76 66 97 52]
 [90 58 81 61]
 [82 69 51 59]
 [89 59 92 84]]
Transpose 
 [[76 90 82 89]
 [66 58 69 59]
 [97 81 51 92]
 [52 61 59 84]]


# 13.

In [49]:
import numpy as np

my_list = list(range(1,26))
my_array = np.array(my_list)
my_array = my_array.reshape(5,5)

my_array = my_array[1:3,2:4]
my_array

array([[ 8,  9],
       [13, 14]])

# 14.

In [52]:
import numpy as np

my_list = list(range(1,26))
my_array = np.array(my_list)
my_array = my_array.reshape(5,5)


my_array = my_array[3,2:5]
my_array

array([18, 19, 20])

# 15.

In [54]:
import numpy as np

my_list = list(range(1,26))
my_array = np.array(my_list)
my_array = my_array.reshape(5,5)


my_array = my_array[3:,0:2]
my_array

array([[16, 17],
       [21, 22]])

# 16.

In [58]:
import numpy as np

my_list = list(range(1,26))
my_array = np.array(my_list)
my_array = my_array.reshape(5,5)

my_array = my_array[3,:]
my_array

array([16, 17, 18, 19, 20])

# 17.

In [59]:
import numpy as np

my_list = list(range(1,26))
my_array = np.array(my_list)
my_array = my_array.reshape(5,5)

my_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# 18.

In [65]:
import numpy as np

my_array = np.random.randint(10,100,(5,5))
my_array

for x in my_array:
    for y in x:
        if y>50:
            print(y)

86
80
87
99
83
87
61
78
75
93
56


# 19.

In [66]:
import numpy as np

my_array = np.random.randint(10,100,(5,5))
my_array

new_list = my_array[my_array>40]
new_list

array([68, 89, 46, 64, 69, 49, 51, 96, 60, 58, 69, 56, 41, 89, 94, 47, 78])

# 20.

In [97]:
import numpy as np

temp = []
def checkRepeat(number):
    if number>10 and number<100:
        
        if len(temp)==0:
            temp.append(number)
        else:
            index = 0
            for y in temp:
                
                if number != y:

                    if index == len(temp)-1:
                        temp.append(number)
                        break

                else:
                    print('เลขซ้ำ กรุณาลองใหม่')
                    break
                index = index+1
    else:
        print('เลขต้องอยู่ระหว่าง 10-100')

while len(temp)<9:
    x = int(input('ป้อนตัวเลข'))
    checkRepeat(x)
my_array = np.array(temp)
my_array = my_array.reshape((3,3))
print('matrix 3x3 \n',my_array)
my_array_transpose = my_array.T
print('transpose \n',my_array_transpose)
print('เลขตำแหน่ง 2,2 : ',my_array_transpose[2,2])
    

ป้อนตัวเลข 11
ป้อนตัวเลข 12
ป้อนตัวเลข 13
ป้อนตัวเลข 14
ป้อนตัวเลข 15
ป้อนตัวเลข 16
ป้อนตัวเลข 17
ป้อนตัวเลข 18
ป้อนตัวเลข 19


matrix 3x3 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]
transpose 
 [[11 14 17]
 [12 15 18]
 [13 16 19]]
เลขตำแหน่ง 2,2 :  19
